Check that we have the required kernel crypto support. This condition may not be the correct behaviour for the ccmp module.

diff --git a/trunk/Makefile b/trunk/Makefile
--- a/trunk/Makefile
+++ b/trunk/Makefile
@@ -179,4 +179,11 @@ configcheck: sanitycheck
 	    exit 1; \
 	fi
 	
+	@# check crypto AES support is enabled for CCMP fallback
+	@if [ -z "$(CONFIG_CRYPTO_AES)" ] || [ -z "$(CONFIG_CRYPTO_AES_586)" ]; then \
+	    echo "FAILED"; \
+	    echo "Please enable an AES crypto module."; \
+	    exit 1; \
+	fi
+	
 	@echo "ok."
