o "install" target no longer depends on "all"   Submitted by: Steve <st3v3@btinternet.com> o restructuring of top-level Makefile.inc o KERNELPATH now tries to fall back to /usr/src/linux for cases where   /lib/modules/$(KERNELRELEASE)/build does not exist o determine KERNELRELEASE from $(KERNELPATH)/Makefile rather than "uname -r",   which allows to build madwifi for other kernel versions than the one that   is currently running; up to now this has been done only for BUS=AHB o kernel extra version added to KERNELRELEASE o new Makefile target "info" that prints some information which may be   useful for debugging compilation problems o new Makefile targets "configcheck" and "dotconfig" which check if the   kernel has been properly configured; target "all" depends on "configcheck",   so this check is automatically performed when building via "make all" o typo fixed

diff --git a/cvs-import/trunk/Makefile b/cvs-import/trunk/Makefile
--- a/cvs-import/trunk/Makefile
+++ b/cvs-import/trunk/Makefile
@@ -46,7 +46,7 @@ include Makefile.inc
 # NB: the order is important here
 DIRS=	${ATH_HAL} ${ATH_RATE} ${WLAN} ${ATH}
 
-all:
+all: configcheck
 	mkdir -p ${SYMBOLSDIR}
 	for i in ${DIRS}; do \
 		(cd $$i; make) || exit 1; \
@@ -78,3 +78,58 @@ clean:
 		(cd $$i; make clean); \
 	done
 	rm -rf ${SYMBOLSDIR}
+
+info:
+	@echo "The following settings will be used for compilation:"
+	@echo "TARGET       : $(TARGET)"
+	@echo "BUS          : $(BUS)"
+	@echo "TOOLPATH     : $(TOOLPATH)"
+	@echo "KERNELRELEASE: $(KERNELRELEASE)"
+	@echo "KERNELPATH   : $(KERNELPATH)"
+	@echo "KERNELCONF   : $(KERNELCONF)"
+	@echo "MODULEPATH   : $(MODULEPATH)"
+	@echo "KMODSUF      : $(KMODSUF)"
+	@echo "DESTDIR      : $(DESTDIR)"
+
+dotconfig:
+	@#
+	@# check if kernel configuration file is available
+	@#	
+	@if [ ! -f $(KERNELCONF) ]; then \
+	    echo "You need to configure your kernel."; \
+	    exit 1; \
+	fi
+
+# new targets should be inserted ABOVE this line in order to avoid
+# problems with the included kernel configuration file below.
+include $(KERNELCONF)
+
+configcheck: dotconfig
+	@#
+	@# check if kernel configuration meets all requirements
+	@#
+	@echo -n "Checking kernel configuration... "
+	
+	@if [ -z "$(CONFIG_SYSCTL)" ]; then \
+	    echo "FAILED"; \
+	    echo "Please enable sysctl support."; \
+	    exit 1; \
+	fi
+	@if [ -z "$(CONFIG_NET_RADIO)" ]; then \
+	    echo "FAILED"; \
+	    echo "Please enable wireless extensions."; \
+	    exit 1; \
+	fi
+	@if [ -z "$(CONFIG_CRYPTO)" ]; then \
+	    echo "FAILED"; \
+	    echo "Please enable crypto API."; \
+	    exit 1; \
+	fi
+	
+	@#
+	@# room for future improvements:
+	@# * check for correct version of wireless.h
+	@# * check for kernel version 2.4.x/2.6.x
+	@#
+	
+	@echo "passed."
